name: "Scrum master to Discord"
description: "Determine the scrum masters for a team and post in webhook discord channel"
inputs:
  team: # id of input
    description: "The list of team members that can be scrum masters"
    required: true
  webhook: # id of second input
    description: "The discord webhook to message"
    required: true
runs:
  using: "node12"
  main: "index.js"
