const core = require("@actions/core");
const fetch = require("node-fetch");

try {
  const team = JSON.parse(core.getInput("team"));
  const webhook = core.getInput("webhook");
  const githubRunNumber = process.env.GITHUB_RUN_NUMBER;
  const githubRunID = process.env.GITHUB_RUN_ID;

  const scrumMasters = determineScrumMasters(
    team,
    githubRunNumber,
    githubRunID
  );
  messageDiscord(webhook, scrumMasters);
} catch (error) {
  core.setFailed(error.message);
}

function determineScrumMasters(team, number, variance = 1) {
  const scrumMasterOne = team.splice(number % team.length, 1);
  const scrumMasterTwo = team.splice((number + variance) % team.length, 1);
  let scrumMasters = scrumMasterOne.concat(scrumMasterTwo);
  return scrumMasters;
}

function messageDiscord(webhook, scrumMasters) {
  fetch(webhook, {
    method: "post",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      username: "Github Action",
      avatar_url:
        "https://media-exp1.licdn.com/dms/image/C510BAQHgfIxjqWSSsQ/company-logo_200_200/0/1519855922416?e=2159024400&v=beta&t=_L2XLMCXeEzSX_c8oBMM_uuEK1kgfno7ViFJXD5BP6U",
      embeds: [
        {
          color: 11730954,
          author: {
            name: "AAU-Dat",
            url: "https://github.com/AAU-Dat",
            icon_url:
              "https://media-exp1.licdn.com/dms/image/C510BAQHgfIxjqWSSsQ/company-logo_200_200/0/1519855922416?e=2159024400&v=beta&t=_L2XLMCXeEzSX_c8oBMM_uuEK1kgfno7ViFJXD5BP6U",
          },
          title: "New Scrum Masters",
          url: "https://github.com/AAU-Dat/scrummaster-discord",
          description: "",
          fields: [
            {
              name: "First master",
              value: scrumMasters[0],
              inline: true,
            },
            {
              name: "Second master",
              value: scrumMasters[1],
              inline: true,
            },
          ],
          footer: {
            text: "Generated by Github Action AAU-dat/scrummaster-discord",
          },
        },
      ],
    }),
  }).catch((err) => console.error(err));
}
